### ISSUE TITLE
compile error 

### ISSUE THREAD

**Issue by 85204** [Jackysi/advancedtomato#159]
> ```
>   link_app.${shlib_target}
> ```
> 
> make[7]: Entering directory `/home/diox/advancedtomato/release/src/router/openssl/apps'
> openssl.o:(.data.rel.functions+0x8): undefined reference to`verify_main'
> openssl.o:(.data.rel.functions+0x14): undefined reference to `asn1parse_main'
> openssl.o:(.data.rel.functions+0x2c): undefined reference to`dgst_main'
> openssl.o:(.data.rel.functions+0x44): undefined reference to `passwd_main'
> openssl.o:(.data.rel.functions+0x50): undefined reference to`errstr_main'
> openssl.o:(.data.rel.functions+0x5c): undefined reference to `ca_main'
> openssl.o:(.data.rel.functions+0x68): undefined reference to`crl_main'
> openssl.o:(.data.rel.functions+0x80): undefined reference to `rsautl_main'
> openssl.o:(.data.rel.functions+0x8c): undefined reference to`dsa_main'
> openssl.o:(.data.rel.functions+0x98): undefined reference to `dsaparam_main'
> openssl.o:(.data.rel.functions+0xa4): undefined reference to`ec_main'
> openssl.o:(.data.rel.functions+0xb0): undefined reference to `ecparam_main'
> openssl.o:(.data.rel.functions+0xc8): undefined reference to`genrsa_main'
> openssl.o:(.data.rel.functions+0xd4): undefined reference to `gendsa_main'
> openssl.o:(.data.rel.functions+0xe0): undefined reference to`genpkey_main'
> openssl.o:(.data.rel.functions+0xec): undefined reference to `s_server_main'
> openssl.o:(.data.rel.functions+0xf8): undefined reference to`s_client_main'
> openssl.o:(.data.rel.functions+0x104): undefined reference to `speed_main'
> openssl.o:(.data.rel.functions+0x110): undefined reference to`s_time_main'
> openssl.o:(.data.rel.functions+0x11c): undefined reference to `version_main'
> openssl.o:(.data.rel.functions+0x128): undefined reference to`pkcs7_main'
> openssl.o:(.data.rel.functions+0x134): undefined reference to `cms_main'
> openssl.o:(.data.rel.functions+0x140): undefined reference to`crl2pkcs7_main'
> openssl.o:(.data.rel.functions+0x14c): undefined reference to `sess_id_main'
> openssl.o:(.data.rel.functions+0x158): undefined reference to`ciphers_main'
> openssl.o:(.data.rel.functions+0x164): undefined reference to `nseq_main'
> openssl.o:(.data.rel.functions+0x170): undefined reference to`pkcs12_main'
> openssl.o:(.data.rel.functions+0x17c): undefined reference to `pkcs8_main'
> openssl.o:(.data.rel.functions+0x188): undefined reference to`pkey_main'
> openssl.o:(.data.rel.functions+0x194): undefined reference to `pkeyparam_main'
> openssl.o:(.data.rel.functions+0x1a0): undefined reference to`pkeyutl_main'
> openssl.o:(.data.rel.functions+0x1ac): undefined reference to `spkac_main'
> openssl.o:(.data.rel.functions+0x1b8): undefined reference to`smime_main'
> openssl.o:(.data.rel.functions+0x1c4): undefined reference to `rand_main'
> openssl.o:(.data.rel.functions+0x1d0): undefined reference to`ocsp_main'
> openssl.o:(.data.rel.functions+0x1dc): undefined reference to `prime_main'
> openssl.o:(.data.rel.functions+0x1e8): undefined reference to`ts_main'
> openssl.o:(.data.rel.functions+0x1f4): undefined reference to `srp_main'
> openssl.o:(.data.rel.functions+0x200): undefined reference to`dgst_main'
> openssl.o:(.data.rel.functions+0x20c): undefined reference to `dgst_main'
> openssl.o:(.data.rel.functions+0x218): undefined reference to`dgst_main'
> openssl.o:(.data.rel.functions+0x224): undefined reference to `dgst_main'
> collect2: ld returned 1 exit status
> make[7]: **\* [link_app.gnu] Error 1

what can I do?
I compile on Ubuntu 12.04.5

**Comment by Jackysi** [comment]
This problem is related to Tomato router firmware, please report it to Shibby. AdvancedTomato is a GUI modification for Tomato and so its not actually a firmware. Issues as previously stated are irrelevant to the Graphical user interface but are actual firmware issues. https://bitbucket.org/pl_shibby/tomato-arm/issues?status=new&status=open!
